name: Create tag

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  tag:
    if: github.event.pull_request.merged == true
    name: Create tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            package.json
          sparse-checkout-cone-mode: false

      - name: Get version
        id: version
        run: echo version=$(cat package.json | jq '.version' -r) >> "$GITHUB_OUTPUT"

      - name: Push tag
        uses: anothrNick/github-tag-action@v1
        env:
          CUSTOM_TAG: "v${{ steps.version.outputs.version }}"
          GITHUB_TOKEN: ${{ secrets.PAT_PUSH_TAG }}
